### ISSUE TITLE
User can search for recipes

### ISSUE THREAD

**Issue by andychen97** [andychen97/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can search for recipes through a search bar.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will type in a food item or type of food that they're looking to make, through one of 2 search bars 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-06-13 at 3 17 48 PM](https://user-images.githubusercontent.com/100327736/173455634-8bd19601-0a01-439e-a623-55544bbd0035.png)
![Screen Shot 2022-06-13 at 3 52 31 PM](https://user-images.githubusercontent.com/100327736/173460569-60b80fc3-15b6-482b-8617-6dfe79a6d56e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a header for the website logo on the left and a search bar on the right
- [x] top search bar expandable when clicked on
- [x] make sure the header is accounted for when looking at the mobile version
- [x] Add a `div[data-view="home-page"]` to the HTML.
- [x] hero image
- [x] text within hero image
- [x] search bar within hero image
- [x] send requests to Tasty API with the search term
- **Clean Up**
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
