### ISSUE TITLE
Users can view results from search term

### ISSUE THREAD

**Issue by andychen97** [andychen97/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can view results from the search terms.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After typing in the desired food item or food type through one of 2 search bars, a result will generate

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-06-14 at 11 38 11 PM](https://user-images.githubusercontent.com/100327736/173759196-f6cdeb89-22fd-4282-b2fb-67b35da45c44.png)
![Screen Shot 2022-06-14 at 11 38 22 PM](https://user-images.githubusercontent.com/100327736/173759205-debe6641-d701-43fb-87c8-f55f7c5dc3c0.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create layout cards
- [x] get image, name
- [x] create DOM tree for cards
- **Clean Up**
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
