### ISSUE TITLE
User can select a food item

### ISSUE THREAD

**Issue by andychen97** [andychen97/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can select a food item.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will be able to click on a recipe and see the ingredients, instructions and info of the food. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-06-13 at 3 54 16 PM](https://user-images.githubusercontent.com/100327736/173460890-8341e867-e828-4f9c-984c-a8d538117bee.png)
![Screen Shot 2022-06-13 at 3 54 09 PM](https://user-images.githubusercontent.com/100327736/173460902-ce37617d-df27-43fb-89f2-b8e043d48e94.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create a div[data-view="recipe-page"]
- [x] add a click addeventlistener for each li element
- [x] create the template of recipes and instructions page
- [x] create dom tree to match the template
- [x] get the necessary information to render the appropriate information 
- [x] add viewswap function
- **Clean Up**
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
