### ISSUE TITLE
User can add food item to their favorite's list

### ISSUE THREAD

**Issue by andychen97** [andychen97/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can add food item to their favorite's list
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will be able to add recipes to their favorite list. 

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create div[data-view="favorites"]
- [x] add favorites icon to nav bar
- [x] add icon to recipe page
- [x] addeventlistener to icon on recipe page
- [x] add favorites property to data list
- [x] viewswap
- **Clean Up**
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
