### ISSUE TITLE
User can view their favorite list

### ISSUE THREAD

**Issue by andychen97** [andychen97/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to view their favorite list

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will be able to see what they have added to their favorite list. 

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create a view for favorites
- [x] update view swapping
- [x] prepend saved recipes from data.favorite to favorite's view
- **Clean Up**
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
